package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	defaultNotebookRoot    string = "."
	defaultOutputDirectory string = "."
	usage                  string = `Usage:
    md-secretary <command> [<options>] <args>

Commands:
    contents <project-name>
        Displays a rundown of every project in a notebook. This rundown
        includes its title, timeline, and abstract.

    create <project-name>
        Creates a new project folder structure in the notebook taking
        a project name for an argument. The resulting project will
        be a folder with the same name (sanitized to be "filesystem-
        friendly"). Within the project, a media folder, project
        file, and its first month folder will also be created. If a
        project with the same name already exists, creation will fail.

    append <project-name>
        Extends an existing project by adding a month folder structure
        to it. The created month folder will contain a log file and
        summary file. If a project with the given name doesn't exist,
        the command will fail.

    scrap <project-name>
        Deletes an existing project after confirming with the user.
        The confirmation can be disabled using the ` + "`--force`" + ` flag. If
        a project with the given name doesn't exist, the command will
        fail.

    import <path-to-json>
        Builds a project from a JSON file generated by the ` + "`export`" + `
        command and adds it to a notebook. If the given JSON file does
        not exist, the command will fail. If a project with the name
        derived from the JSON file already exists, the command will
        indicate the conflict to the user and confirm with them that
        they want to overwrite the existing version. The ` + "`--force`" + `
        flag will disable this confirmation.

    export <project-name>
        Generates a JSON file that describes the current state of a
        project with the given name. This can be useful for sharing
        long projects between notebooks. All media will be encoded as
        Base64. If the ` + "`--transfer`" + ` flag is provided, the project will
        also be removed from the current notebook, as it is implied that
        the project will not be returning. If no project with the given
        name exists, the command will fail.

    help
        Displays this help message and exists.

Options:
    --path, -p <path-to-notebook>
        Specifies the path to a notebook. By default, the current
        working directory is used.

    --force, -f
        When using the ` + "`scrap`" + ` or ` + "`import`" + ` command, this will disable
        any confirmation and perform the operation automatically. Use
        this flag with caution. Otherwise, this has no effect.

    --output, -o <path-to-output-location>
        When using the ` + "`export`" + ` command, this specfies the output path
        to the generated JSON file. Otherwise, this has no effect.
        Default is the current working directory.

    --transfer, -t
        When using the ` + "`export`" + ` command, this removes the project from
        the notebook after generating the JSON file.

    --help, -h
        Displays this help message and exits, ignoring all other input. It
        usually makes more sense to simply execute the ` + "`help`" + ` command.`
)

var (
	path     string
	force    bool
	transfer bool
	output   string
)

func main() {
	// handle help request before anything else
	for _, arg := range os.Args {
		if arg == "--help" || arg == "-h" {
			fmt.Println(usage)
			return
		}
	}

	// check if no command is specified
	if len(os.Args[1:]) == 0 || strings.HasPrefix(os.Args[1], "-") {
		fmt.Println("No command specified.")
		fmt.Println(usage)
		return
	}

	// parse arguments
	flag.StringVar(&path, "path", filepath.Clean(defaultNotebookRoot), "")
	flag.StringVar(&path, "p", filepath.Clean(defaultNotebookRoot), "")
	flag.BoolVar(&force, "force", false, "")
	flag.BoolVar(&force, "f", false, "")
	flag.BoolVar(&transfer, "transfer", false, "")
	flag.BoolVar(&transfer, "t", false, "")
	flag.StringVar(&output, "output", filepath.Clean(defaultOutputDirectory), "")
	flag.StringVar(&output, "o", filepath.Clean(defaultOutputDirectory), "")
	flag.Parse()

	// only one or the other will be used each run
	projectName := flag.Arg(1)
	pathToJson := filepath.Clean(flag.Arg(1))

	switch cmd := os.Args[1]; cmd {
	case "contents":
		handleContents(projectName, path)
	case "create":
		handleCreate(projectName, path)
	case "append":
		handleAppend(projectName, path)
	case "scrap":
		handleScrap(projectName, path, force)
	case "import":
		handleImport(pathToJson, path, force)
	case "export":
		handleExport(projectName, path, transfer)
	case "help":
		handleHelp()
	default:
		fmt.Printf("Invalid command: `%s`\n", cmd)
		fmt.Println(usage)
	}
}

func handleContents(projectName string, path string) {
	fmt.Println("contents")
}

func handleCreate(projectName string, path string) {
	fmt.Println("create")
}

func handleAppend(projectName string, path string) {
	fmt.Println("append")
}

func handleScrap(projectName string, path string, force bool) {
	fmt.Println("scrap")
}

func handleImport(projectName string, path string, force bool) {
	fmt.Println("import")
}

func handleExport(projectName string, path string, transfer bool) {
	fmt.Println("export")
}

func handleHelp() {
	fmt.Println(usage)
}
