# This is the root default configuration for the application. This is
# embedded directly into the binary at build time, so it cannot be
# directly modified by the end user. However, the values can be
# overridden by a custom TOML file using the `--config` option.

# When using the CLI, sets desired width of the output in characters.
# This ensures that the output looks halfway decent in an kina-flexible
# manner.
display-width = 72

# Configuration of project files.
[project]

    # Abstract placeholder for newly-generated projects.
    abstract-template = """\
        Briefly summarize the gist of the project by providing some \
        big-picture goals. Someone who knows nothing about this \
        should have a good understanding about it after reading this \
        abstract."""

    # Resources placeholder for newly-generated projects.
    resources-template = '''
* Resources that are directly applicable go here...
* Another resource...'''

    # Further reading placeholder for newly-generated projects.
    further-reading-template = """
* Resources that are indirectly applicable go here...
* Another resource..."""

# Configuration of log files.
[log]

    # Content placeholder in log files for newly-generated projects.
    content-template = '''
* Brain dump goes here.
    * Anything interesting that you find at all.
    * It does not matter if it is that important, it could be useful!
* Brain dumps are awesome.
    * Everyone should do this...'''

# Configuration of summary files.
[summary]

    # Summary placeholder in summary files for newly-generated projects.
    summary-template = """\
        Here goes a summary of a big milestone that occured during \
        this month."""

    # Content placeholder in summary files for newly-generated projects.
    content-template = '''
* Milestones go here.
    * Any elaboration for this milestone is appreciated.
* If something else really cool happened, do not be shy!
* Why is this a really important milestone?'''

# Configuration of notebooks.
[notebook]

    # Path to the notebook root. Typically, the configuration file
    # exists within the notebook root, so the default is the current
    # working directory.
    path = 'notebook'

    # Indicates whether or not to use a compact naming convention when
    # a project is extended another month. Take "January, 2022" as an
    # example. When this value is set to `compact`, the resulting marker
    # directory will be called "jan-22"; when `comfortable`, it will be
    # called "january-2022".
    compact-marker-directory = 'compact'

# Configuration of the compression process.
[compression]

    # Directory to output a compressed project JSON file to.
    path = '.'

    # Naming convention for the generated JSON file after compression.
    # There are two dynamic values that can be used here: `$project` and
    # `$date`.
    #
    # The `$project` placeholder is replaced by a "filesystem-friendly"
    # version of the project title.
    #
    # The `$date` placeholder is replaced by the date at the time of
    # compression in the format "MM-DD-YYYY".
    #
    # Let's say the project title is "My Project" and the current date
    # is January 01, 2022. The following examples show how the name will
    # turn out...
    #
    #    json-title = 'foo'            -> "foo.json"
    #    json-title = '$project'       -> "my-project.json"
    #    json-title = '$date'          -> "01-01-2022.json"
    #    json-title = '$project-$date' -> "my-project-01-01-2022.json"
    #    json-title = '$date-$date'    -> "01-01-2022-01-01-2022.json"
    #
    # One can see that these two placeholders can be used together in
    # any order and any number of time, though that may be a bit
    # pointless. Note that any internal spaces will be converted to
    # hyphens automatically and external spaces will be removed...
    #
    #    json-title = '    f o  o  '   -> "f-o--o.json"
    #
    # This is to ensure compatibility with the operating system.
    # json-title = '$project-$date'
    json-title = '    d.e-$projectoffer.json-$date---h'
